### ISSUE TITLE
Error while trying the event component

### ISSUE THREAD

**Issue by vandalon** [andreypopov/node-red-contrib-deconz#1]
Hi,

First af all, thank you very much for creating this plugin. I was waiting for this :P

Initial setup works perfect.
When testing it out I'm getting the following error when trying to listen to events.

I'm running HassIO with the node-red addon. 

```
19 Jun 11:21:02 - [red] Uncaught Exception:
19 Jun 11:21:02 - TypeError: Cannot read property '00:17:88:01:10:3e:89:66-02-fc00' of undefined
    at WebSocket.<anonymous> (/config/node-red/node_modules/node-red-contrib-deconz/deconz.js:569:89)
    at WebSocket.emit (events.js:182:13)
    at Receiver.receiverOnMessage (/config/node-red/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.dataMessage (/config/node-red/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (/config/node-red/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (/config/node-red/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (/config/node-red/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
[19/Jun/2019:11:21:02 +0200] 101 192.168.1.42, 172.30.32.1(172.30.32.2) GET /comms HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hassio-addon-node-red@ start: `node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hassio-addon-node-red@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-19T09_21_02_507Z-debug.log
```

**Comment by andreypopov** [comment]
which version? 

![2019-06-30_10-50-27](https://user-images.githubusercontent.com/1624839/60393902-f3a02f00-9b24-11e9-865c-fcca97e86046.png)

**Comment by vandalon** [comment]
Just tested with 0.8.0 and the issue still is there :)

**Comment by wovka88** [comment]
Same Issue with HassOS, also with 0.8.1 :(

**Comment by andreypopov** [comment]
try on 0.8.3 , and post error log here

**Comment by wovka88** [comment]
No crashes anymore. Thanks :) 

But there is a problem with the hass.io ingress mode (embed), the device list is empty and there are no errors. If i access the node red interface directly it works 👍 do you have any ideas?

**Comment by wovka88** [comment]
I found the Issue, it calls the wrong API Url for deconz:

It tries this one: http://192.168.178.100:8123/deconz/itemlist?controllerID=XXXXXX.XXXXXX&forceRefresh=false  and get 404

but the right address is:
http://192.168.178.100:8123/api/hassio_ingress/uniqueidxxxxxxxxxxxx/deconz/itemlist?controllerID=XXXXXX.XXXXXX&forceRefresh=false

**Comment by andreypopov** [comment]
I can add it as setting.
**API Path**

**Comment by wovka88** [comment]
maybe it is enough to change var NODE_PATH = '/deconz/'; to var NODE_PATH = 'deconz/'; ?

**Comment by wovka88** [comment]
ok, its not working :( tried it .. i think it should work automatically but somethink is wrong with the Home Assitant Ingress Api call

**Comment by andreypopov** [comment]
I will check what is hassio ingress.

**Comment by wovka88** [comment]
node-red-contrib-deconz-helpers.js
changed line 26 to:             $.getJSON('deconz/itemlist', {
changed line 186 to:             $.getJSON('deconz/statelist', {

now its working :)

**Comment by andreypopov** [comment]
works for me too

**Comment by wovka88** [comment]
Maybe line 2 must be also edited?     $.getJSON('/deconz/gwscanner', {})

i don't now the function for this..

**Comment by andreypopov** [comment]
try new 0.9.1 version

**Comment by wovka88** [comment]
thanks, works fine

**Comment by vandalon** [comment]
Working for me now as wel. Thanks!

**Comment by vandalon** [comment]
I have to come back on this. Although I don't get any errors, I also don't see any events  with the debug node :)

**Comment by andreypopov** [comment]
version? bug was in 10.0, then fixed
