### ISSUE TITLE
In Node: Output only on change option.

### ISSUE THREAD

**Issue by vandalon** [andreypopov/node-red-contrib-deconz#10]
** Describe your idea here**

Hi again :)
It would be great to have an option within the in node that it outputs only when state is changed. Now I get output on every poll. This can be an issue with motion sensors where for example a timer is started when the sensors stops detecting motion. This timer now gets restarted everytime the sensor outputs a false.

In the image below you see the debug output of 2 sensors:

<img width="302" alt="image" src="https://user-images.githubusercontent.com/3370317/60924704-1e675180-a2a2-11e9-9c57-476fe6c6d291.png">

**Comment by andreypopov** [comment]
I will check it.

use RBE node

**Comment by vandalon** [comment]
I'm actually trying to implement this myself. I'll sent a pull request if I can get it done so you can see if you like it. I figured with all my feature request I should do some work myself :)

**Comment by vandalon** [comment]
#17

**Comment by vandalon** [comment]
Fixed with #17
