### ISSUE TITLE
Node-Red shows warnings when using deconz plugin

### ISSUE THREAD

**Issue by vandalon** [andreypopov/node-red-contrib-deconz#11]
Node-Red trows the following warnings when using the deconz plugin.

(node:489) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 onClose listeners added. Use emitter.setMaxListeners() to increase limit
(node:489) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 onSocketError listeners added. Use emitter.setMaxListeners() to increase limit
(node:489) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 onSocketClose listeners added. Use emitter.setMaxListeners() to increase limit
(node:489) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 onSocketOpen listeners added. Use emitter.setMaxListeners() to increase limit
(node:489) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 onSocketPongTimeout listeners added. Use emitter.setMaxListeners() to increase limit
(node:489) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 onNewDevice listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by andreypopov** [comment]
how to reproduce? is this after several deploys?

**Comment by vandalon** [comment]
Yes, after every deploy and on startup.

**Comment by vandalon** [comment]
Could be linked with the amount of sensors and lights i have in node-red

**Comment by andreypopov** [comment]
how do u deploy, full flow or only modified nodes?

**Comment by andreypopov** [comment]
Cant reproduce, I have only 2 devices:) 
I can remove events (onClose) and replace with function

**Comment by vandalon** [comment]
I did not now there where different ways to deploy, but I deploy full flow I think.

**Comment by vandalon** [comment]
I can (and will :)) test for you

**Comment by andreypopov** [comment]
> Could be linked with the amount of sensors and lights i have in node-red

https://github.com/andreypopov/node-red-contrib-deconz/issues/12
post screen of your list here, pls

**Comment by vandalon** [comment]
do you need an onclose* in every node? Is it not the server.js that opens en closes connections?

**Comment by andreypopov** [comment]
I need event, when node looses connection
server.js opens only one connection
I will try to use  node.on('close' in every node

**Comment by vandalon** [comment]
i'll check if that works :)

**Comment by vandalon** [comment]
Why can't we use the output of the one connection from server.js for every node? (i'm just being curious here :))

**Comment by vandalon** [comment]
I see, but with events enabled it should be possible, right?

**Comment by vandalon** [comment]
replacing node.server.on with node.on does not work , but maybe that's not what you meant :)

**Comment by andreypopov** [comment]
fixed
