### ISSUE TITLE
Deconz simple on/off outlet with HomeKit 

### ISSUE THREAD

**Issue by koburg** [andreypopov/node-red-contrib-deconz#110]
** Describe issue **
I need som help to fix this. I have some simple on/off plugs. when I try to set it up I can make it work with
on/off toggle command from the HomeKit UI command.

But when I manually switch on/off the plug with the button on the plug it goes crazy on/off on/off etc etc forever
what am I doing wrong.

NB. i have tried both outlet and switch no difference.

** Screens / Logs **

<img width="914" alt="Skærmbillede 2021-01-02 kl  19 50 00" src="https://user-images.githubusercontent.com/3473374/103464512-7dd9dc80-4d34-11eb-90d2-4e289b64f5af.png">

<img width="481" alt="image" src="https://user-images.githubusercontent.com/3473374/103464533-a661d680-4d34-11eb-85a6-741877b54c59.png">

<img width="487" alt="image" src="https://user-images.githubusercontent.com/3473374/103464539-ba0d3d00-4d34-11eb-9c05-408b238daf03.png">

** Hardware / Software **
  - raspberry 4   
  - version of deconz gateway: [2.09.00 / 14.9.2020] 
  - version of node-red-contrib-deconz: [1.2.0]

**Comment by grishmanCH** [comment]
Hello, @koburg! You are using wrong output on Homekit node, you need to use upper output. So this issue is most probably not related to deconz node. If so, please close the issue.

**Comment by koburg** [comment]
Yes I saw this later on. 
you have made a really good node.

But since many developers not are making all documentation/examples then it can take time to
find how it is working.

**Comment by TheNON75** [comment]
Hi @koburg there is a documentation available for nrchkb ;)

_Currently, there are two main and one conditional output port for homekit-service in node-red.
1. onChange, is fired when a value has been changed, this is the most recommended to use for most cases.
2. onSet, is fired every time a value has been set (even to the same value as before), it is used to capture repeated input like Television remote buttons.
3. camera snapshot, is enabled only for CameraController Service and is used to retrieve camera snapshot data_
