### ISSUE TITLE
Sort, group devices in ItemsList

### ISSUE THREAD

**Issue by andreypopov** [andreypopov/node-red-contrib-deconz#12]
** Describe your idea here**
Possible problem, when there are big amount of items.
![2019-07-10_11-48-04](https://user-images.githubusercontent.com/1624839/60955003-a4b67e80-a308-11e9-81a5-ddb2f49f53c9.png)

**Comment by andreypopov** [comment]
Any ideas how to deal with it?

**Comment by vandalon** [comment]
Just out of the top of my head, without looking at the code, I'd say first load the complete list in memory (array or list), then sort it, then output it to the node

**Comment by andreypopov** [comment]
how to sort/group? 

--Sensors
-----MultiSensor 1
--------ZHATemperature
--------ZHAHumidity
-----MultiSensor 2


--Lights
-----Light 1
-----Light 1

**Comment by vandalon** [comment]
That sounds sensible yes. and light groups could be included under lights I think. (where applicable)

**Comment by vandalon** [comment]
Sorting alphabetically now done in #25 

I will look into the sorting method as mentioned above as well :)

**Comment by andreypopov** [comment]
great work, improved since 0.11.0
