### ISSUE TITLE
Auto discovery finding the same gateway twice

### ISSUE THREAD

**Issue by Marlor** [andreypopov/node-red-contrib-deconz#156]
** Describe issue **
Auto discovery is finding the same gateway twice on Home Assistant OS + deconz addon

** Screens / Logs **

```
Fetching data from 'https://phoscon.de/discover'.
Found 1 gateways from 'https://phoscon.de/discover'.
Looking for gateways at 5 locations.
Found gateway ID "00212EFFFF0428DB" at "http://172.30.33.2:40850/api/".
Found gateway ID "00212EFFFF0428DB" at "http://core-deconz.local.hass.io:40850/api/".
Found 2 gateways.
Got mutiple result and no choice has already been made.
[{"bridge_id":"00212EFFFF0428DB","name":"Home","secured":false,"ip":"172.30.33.2","port":40850},{"bridge_id":"00212EFFFF0428DB","name":"Home","secured":false,"ip":"core-deconz.local.hass.io","port":40850}]
```

** Hardware / Software **
  - Home Assistant OS 6.4 generic-x86-64
  - version of deconz addon: 6.10.0
  - version of deconz: 2.12.6
  - version of Node-RED Addon: 10.0.1
  - version of Node-RED: 2.0.6
  - version of node-red-contrib-deconz: 2.0.2

**Comment by Zehir** [comment]
Because the autodiscovery get the ip address of the deconz container from inside of the home assistant docket environement I added some IP to search deconz api.
But yes I could filter duplicates, I will fix that next time.
