### ISSUE TITLE
Get node "node error" for "complete payload" output with multiple devices

### ISSUE THREAD

**Issue by thomasvnl** [andreypopov/node-red-contrib-deconz#157]
** Describe issue **
Deconz get node goes into "node error" when multiple device types (ZHATemperature, ZHAHumidity, ZHAPressure) of the same device (Aqara DHT sensor in this case) are selected and the output is set to "complete payload" in format "Single x... y... z"

** Your flow here **
The screens describe it best

** Screens / Logs **

![image](https://user-images.githubusercontent.com/2838263/136856726-e08fc06d-4ed0-4ccb-8bf6-36f3173c7664.png)

![image](https://user-images.githubusercontent.com/2838263/136856923-f6292c71-b528-4834-99c0-f7eaa51eda6d.png)

** Hardware / Software **
  - raspberry 4 
  - version of deconz gateway: 2.12.06 / 8/19/2021
  - version of node-red-contrib-deconz: 2.0.2

**Comment by thomasvnl** [comment]
> Hi, can you check the node red logs the related logs to this errors ? Wven the node display à "node error" he write some debugs logs too

Hi Zehir. I shall provide these logs around 20:00 CEST today.

**Comment by Zehir** [comment]
> > Hi, can you check the node red logs the related logs to this errors ? Wven the node display à "node error" he write some debugs logs too
> 
> Hi Zehir. I shall provide these logs around 20:00 CEST today.

I dont be able to work on it before 21:00 CEST anyways

**Comment by Zehir** [comment]
What version of node red are you using ?
