### ISSUE TITLE
Turn on/off with brightness values does not work in 2.x

### ISSUE THREAD

**Issue by raddi** [andreypopov/node-red-contrib-deconz#160]
So with the new 2.x version, i can't get my dimmable lights to turn on or off with just the brightness values. All of my node-red flows are useless and i cannot figure out how to repair them. In Version 1.x i could simply set the lights to "brightness" and send values between 0 and 255 to change the brightness, when sending 0, turning the lights off and all values greater 0 would turn the lights on. How do i implement this feature in version 2.x?

Thanks in advance.

**Comment by raddi** [comment]
Okay so i "fixed" this by adding 2 instances of the same dimmable light and a switch node to separate 0 from >0 values and then set one instance to "off" and listen to brightness and one to "on" and listen to brightness. Next thing is, i can't control my window cover anymore, i will open another bug report.

**Comment by schweighart** [comment]
There is a better way than adding two instances of the same light. I configured my lights this way:
![light](https://user-images.githubusercontent.com/3264718/141697687-27173ace-a6f3-469b-a33c-8d7dd76cfbe3.png)
And added a function node upfront with the following code:
```
if (msg.payload>0) {
    return { onoff:true, payload:msg.payload };
} else {
    return { onoff:false };
}
```

**Comment by Zehir** [comment]
> There is a better way than adding two instances of the same light. I configured my lights this way: ![light](https://user-images.githubusercontent.com/3264718/141697687-27173ace-a6f3-469b-a33c-8d7dd76cfbe3.png) And added a function node upfront with the following code:
> 
> ```
> if (msg.payload>0) {
>     return { onoff:true, payload:msg.payload };
> } else {
>     return { onoff:false };
> }
> ```

Yes for some device the brightness 0 is not always off, sometime it's minimum brightness.

But you can do something like this : 
![image](https://user-images.githubusercontent.com/845225/141841340-6721edbe-147a-4982-afdc-4ae2cd55d389.png)

**Comment by schweighart** [comment]
Thanks. Your solution is awesome. I didn't know that I can use operators in this field.
