### ISSUE TITLE
Philips Hue dimmer switch

### ISSUE THREAD

**Issue by arozhankov** [andreypopov/node-red-contrib-deconz#2]
Hello!

Please add charge status for battery node to device "Philips Hue dimmer switch"

=====

Привет.

Пожалуйста добавьте статус заряда батареи в ноде "battery" для устройства "Philips Hue dimmer switch". Сейчас это устройство просто не видно в списке устройств в настройках данной ноды.

**Comment by andreypopov** [comment]
please, show output1 (complete debug message)

**Comment by arozhankov** [comment]
Opsss... Please sorry! 

I was too hasty - in a few minutes the device appeared.
