### ISSUE TITLE
Отсутствие связи про частичном перестроении нодов

### ISSUE THREAD

**Issue by arozhankov** [andreypopov/node-red-contrib-deconz#28]
Привет.

Обнаружил странное поведение нодов.

Пытаюсь считать состояние устройства. Для этого либо копирую, либо настраиваю новый год "in", выбрав нужное устройство и параметр (см. пример ниже).

В настойках состояние показано корректно. Однако после деплоя нод не отдает ничего на выход. Также у нового нода отсутствует статус (под ним).

Решается проблема - полной перестройкой (всех нодов) либо перезагрузкой node-red.

** Hardware / Software **
  - raspbian
  - version of deconz gateway: [2.05.66 / 16/06/2019] 
  - version of node-red-contrib-deconz: [0.11.2]

=======
Hey.

Found strange behavior of nodes.

I'm trying to count the status of the device. To do this, either copy or customize the new node "in" by selecting the desired device and parameter (see the example below).

In the settings of the device, the status is shown correctly. However, after the deployment, the node does not give anything out. Also, the new node has no status (under it).

The problem is solved only - a complete deploy (of all nodes) or a node-red restart.
    
=======
[
    {
        "id": "aae03a0b.9f65a8",
        "type": "switch",
        "z": "634c8fff.b910e8",
        "name": "On/Off?",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "true"
            },
            {
                "t": "false"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 2,
        "x": 1100,
        "y": 680,
        "wires": [
            [
                "2c13091e.a392f6"
            ],
            [
                "5846f9be.12ccb8"
            ]
        ]
    },
    {
        "id": "2c13091e.a392f6",
        "type": "change",
        "z": "634c8fff.b910e8",
        "name": "Flow True",
        "rules": [
            {
                "t": "set",
                "p": "Light_Study",
                "pt": "flow",
                "to": "true",
                "tot": "bool"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1240,
        "y": 660,
        "wires": [
            []
        ]
    },
    {
        "id": "5846f9be.12ccb8",
        "type": "change",
        "z": "634c8fff.b910e8",
        "name": "Flow False",
        "rules": [
            {
                "t": "set",
                "p": "Light_Study",
                "pt": "flow",
                "to": "false",
                "tot": "bool"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1250,
        "y": 700,
        "wires": [
            []
        ]
    },
    {
        "id": "a0261178.d4776",
        "type": "debug",
        "z": "634c8fff.b910e8",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "x": 1100,
        "y": 800,
        "wires": []
    },
    {
        "id": "12265ea5.624bc1",
        "type": "deconz-input",
        "z": "634c8fff.b910e8",
        "name": "",
        "server": "eeee5052.8cc1a8",
        "device": "00:15:8d:00:03:49:be:6c-03",
        "device_name": "Study Main : Smart plug",
        "state": "on",
        "output": "always",
        "outputAtStartup": true,
        "x": 810,
        "y": 660,
        "wires": [
            [
                "aae03a0b.9f65a8",
                "a0261178.d4776"
            ],
            []
        ]
    },
    {
        "id": "eeee5052.8cc1a8",
        "type": "deconz-server",
        "z": "",
        "name": "Conbee2-AR",
        "ip": "10.0.1.100",
        "port": "8080",
        "apikey": "C0F72B7881",
        "ws_port": "8088"
    }
]

**Comment by vandalon** [comment]
Please report in English so other people can also understand

**Comment by arozhankov** [comment]
> Please report in English so other people can also understand

1. You need to open any browser available to you.

2. In the address bar of this browser print .. this is the action when the tip of the finger of the hand touches the desired key ... these are plastic (most often) small squares on the keyboard ...
So, in the address bar of this browser, type the necessary letters to make it: translate.google.com

3. Next, in the field on the left, copy the desired text, select "the great and mighty Russian language", and above the right margin, select "English".

4. Whoosh, whoosh! Magic! And you get quite normal English text.

**Comment by vandalon** [comment]
I tried that, but it was still hard to understand :P

**Comment by vandalon** [comment]
But Also, people search and creating issues on github might be able to find this post when in english. This can prevent duplicate issues and also people to solve their issue without opening a new issue :)

**Comment by arozhankov** [comment]
> But Also, people search and creating issues on github might be able to find this post when in english. This can prevent duplicate issues and also people to solve their issue without opening a new issue :)

poor non english speaking people. how hard is it for them to search for something on github
/ crying /

**Comment by arozhankov** [comment]
> Please report in English so other people can also understand

Do you not have something against non-English-speaking people? homosexuals? Blacks? Asians? Transvestites?

Now I will closely follow your comments....!

**Comment by arozhankov** [comment]
Bro! I'm just in the mood for jokes :-)
I added English text.

**Comment by vandalon** [comment]
Hmm now I get it. The server node sends data to the other nodes. So might it be that this only works correctly after a full deploy?

**Comment by andreypopov** [comment]
yes, start output works on node-red start, or full deploy, please check

**Comment by arozhankov** [comment]
> yes, start output works on node-red start, or full deploy, please check
Сan I don't deploy only modified nodes?

**Comment by andreypopov** [comment]
yes, server node issue, I will check it deeper

**Comment by andreypopov** [comment]
> > yes, start output works on node-red start, or full deploy, please check
> > Сan I don't deploy only modified nodes?

please, test with v0.11.4
check for duplicated outputs (when node outputs the same message several times - it is bug)

**Comment by andreypopov** [comment]
also fixed for battery

**Comment by andreypopov** [comment]
confirmed that it was fixed

**Comment by arozhankov** [comment]
> > > yes, start output works on node-red start, or full deploy, please check
> > > Сan I don't deploy only modified nodes?
> 
> please, test with v0.11.4
> check for duplicated outputs (when node outputs the same message several times - it is bug)

Great! You're the best!!!
