### ISSUE TITLE
Create option to passtrough the data from a node before get node. 

### ISSUE THREAD

**Issue by vandalon** [andreypopov/node-red-contrib-deconz#29]
I would be a nice feature to have an option the have the output of the getnode just passtrough the payload coming in on the input. This would be usefull to things like pass message trough if light is on only. this would also mean we need to change the workings of the get node so it can handles such checks :)

**Comment by andreypopov** [comment]
done
![2019-10-11_18-01-45](https://user-images.githubusercontent.com/1624839/66664030-77a1a100-ec54-11e9-8f5d-ed105408504b.png)

**Comment by andreypopov** [comment]
![2019-10-11_18-26-08](https://user-images.githubusercontent.com/1624839/66664115-a0299b00-ec54-11e9-9356-d278209c1d27.png)
