### ISSUE TITLE
monitor groups

### ISSUE THREAD

**Issue by MattL0** [andreypopov/node-red-contrib-deconz#3]
Hi, Do you think you'll be able to create a node to monitor the groups states ?

thank you

**Comment by andreypopov** [comment]
hi, event node is not enough?
what do u want to get in payload ?

**Comment by vandalon** [comment]
I think he means that it would be possible to select a light group with the in node. 
So that you can have action when a single light within one group turns on. At least that is something I would like to see ;)

**Comment by andreypopov** [comment]
When I turn on group I receive several events:

1) event for every light in group
![2019-07-09_20-22-20](https://user-images.githubusercontent.com/1624839/60909607-54e3a300-a287-11e9-8a91-67ea721e995a.png)

2) unknown group id, I dont know what is it
![2019-07-09_20-22-28](https://user-images.githubusercontent.com/1624839/60909623-5f9e3800-a287-11e9-9b3d-700bba1dfd08.png)

3) event for my group, we have 2 options in state: all_on and any_on
![2019-07-09_20-20-46](https://user-images.githubusercontent.com/1624839/60909507-11893480-a287-11e9-9d61-3f9fa7537805.png)

**Comment by vandalon** [comment]
#14

**Comment by vandalon** [comment]
Fixed in #14 and #21

**Comment by vandalon** [comment]
Fixed with #14 and #21 but only for get node

**Comment by vandalon** [comment]
This should be resolved via #23

**Comment by vandalon** [comment]
#23 had bugs and I did a refactor of the group handling, should now working better in #25

**Comment by vandalon** [comment]
@MattL0 Can you please check if your issue is resolved and if so, close the issue?

**Comment by andreypopov** [comment]
install 0.11.0

**Comment by MattL0** [comment]
I'll wait for .11 sorry

**Comment by MattL0** [comment]
is group only available via polling?

**Comment by andreypopov** [comment]
already published, wait for npm or

cd ~/.node-red
npm install node-red-contrib-deconz@0.11.0
node-red-stop
sudo npm cache clean --force
node-red-start

**Comment by vandalon** [comment]
No, in 0.11 a group is seen as a meta-device and handled as such. So updates also via websocket

**Comment by MattL0** [comment]
Thanks !! works perfect !!

**Comment by MattL0** [comment]
I'll do another topic to poll the characteristics of groups , I think it is not available for websocket?

**Comment by andreypopov** [comment]
try GET node, complete msg debug node
![2019-07-23_09-54-56](https://user-images.githubusercontent.com/1624839/61689558-18f11900-ad30-11e9-8b19-c32e52ae688e.png)

**Comment by MattL0** [comment]
yes it is under action !thanks Now i should be able to drop the plugin at HomeSeer and use this .  ( and the json api for output for now ).

**Comment by MattL0** [comment]
aww , So output node works now? just tried it.

**Comment by vandalon** [comment]
Output node works how?

**Comment by MattL0** [comment]
i am able to control light with the output node on github it was written that it did not work.

**Comment by vandalon** [comment]
I can't remember that not working :)
