### ISSUE TITLE
Support for Friends of Hue switches (Extra button compared to the currently supported 5 buttons)

### ISSUE THREAD

**Issue by wilpie** [andreypopov/node-red-contrib-deconz#30]
It would be very nice to have support for an additional (6th) button in the IN node.
Currently it only seems to support 5 buttons. The Friends of Hue switches of VIMAR, BUSCH-JEAGER etc. have 4 physical buttons, but pressing the upper two / lower two buttons together also counts as a button press and therefore should result in a code for button 5 or button 6. See also: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1454. I already get the button event for button 5, but not yet for button 6. Thanks in advance, Robert.
(And thanks soo much for the work already done on this component!!!)

**Comment by andreypopov** [comment]
![photo_2019-09-09_15-39-48](https://user-images.githubusercontent.com/1624839/64531572-84ab3780-d318-11e9-9456-c4d06a5b496d.jpg)

 this?

**Comment by wilpie** [comment]
Hi Andreypopov,

It's the https://www.busch-jaeger.de/nl/producten/productoplossing/afstandsbediening/friends-of-hue/ switch. Also sold by Vimar and I believe it's also in the HUE tab.

I've made modifications to the **in.js** node to accomplish what I wanted. I added an extra check at line 211, "else if ([6001, 6002, ....") and inserted an extra column on line 198 - 203 for the codes 6002, 6004, 6001, 6005, 6006, 6010 at the end of each array.

For me, this was all that I needed. After a reboot of the node-red docker instance in which I made the changes, the messages started to come through.

Regards,

Robert

**Comment by andreypopov** [comment]
pull request?

**Comment by wilpie** [comment]
I didn't clone your repos yet, and to set such up will take a while. When back at home tonight I'll copy the changed lines 198-203 + the extra line 211 in this thread. Hope that's okay for you?

Robert.

**Comment by andreypopov** [comment]
where are your changes?

**Comment by wilpie** [comment]
Hi Andrey,

Apologies for the long waiting. Starting at position 187 of “in.js”, my code is the following:

                    if (state['buttonevent'] !== undefined) {
                        //https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi-WXKG01LM
                        // Event        Button        Action
                        // 1000            One            initial press
                        // 1001           One            single hold
                        // 1002            One            single short release
                        // 1003            One            single hold release
                        // 1004           One            double short press
                        // 1005            One            triple short press
                        // 1006            One            quad short press
                        // 1010            One            five+ short press
                        if ([1002, 2002, 3002, 4002, 5002, 6002].indexOf(state['buttonevent']) >= 0) characteristic.ProgrammableSwitchEvent = 0;
                        else if ([1004, 2004, 3004, 4004, 5004, 6004].indexOf(state['buttonevent']) >= 0) characteristic.ProgrammableSwitchEvent = 1;
                        else if ([1001, 2001, 3001, 4001, 5001, 6001].indexOf(state['buttonevent']) >= 0) characteristic.ProgrammableSwitchEvent = 2;
                        else if ([1005, 2005, 3005, 4005, 5005, 6005].indexOf(state['buttonevent']) >= 0) characteristic.ProgrammableSwitchEvent = 3;
                        else if ([1006, 2006, 3006, 4006, 5006, 6006].indexOf(state['buttonevent']) >= 0) characteristic.ProgrammableSwitchEvent = 4;
                        else if ([1010, 2010, 3010, 4010, 5010, 6010].indexOf(state['buttonevent']) >= 0) characteristic.ProgrammableSwitchEvent = 5;

                        if (no_reponse) characteristic.ProgrammableSwitchEvent = "NO_RESPONSE";

                        //index of btn
                        if ([1001, 1002, 1004, 1005, 1006, 1010].indexOf(state['buttonevent']) >= 0) characteristic.ServiceLabelIndex = 1;
                        else if ([2001, 2002, 2004, 2005, 2006, 2010].indexOf(state['buttonevent']) >= 0) characteristic.ServiceLabelIndex = 2;
                        else if ([3001, 3002, 3004, 3005, 3006, 3010].indexOf(state['buttonevent']) >= 0) characteristic.ServiceLabelIndex = 3;
                        else if ([4001, 4002, 4004, 4005, 4006, 4010].indexOf(state['buttonevent']) >= 0) characteristic.ServiceLabelIndex = 4;
                        else if ([5001, 5002, 5004, 5005, 5006, 5010].indexOf(state['buttonevent']) >= 0) characteristic.ServiceLabelIndex = 5;
                        else if ([6001, 6002, 6004, 6005, 6006, 6010].indexOf(state['buttonevent']) >= 0) characteristic.ServiceLabelIndex = 6;

                    }

Kind regards,

Robert

**Comment by andreypopov** [comment]
+ node-red-contrib-deconz@1.1.3
