### ISSUE TITLE
Can't get deconz-server node working

### ISSUE THREAD

**Issue by Parufito** [andreypopov/node-red-contrib-deconz#33]
### Issue
After installing and configuring deconz-server on docker like this. (also deploying)
![Captura de pantalla de 2019-09-22 21-18-05](https://user-images.githubusercontent.com/13435862/65393251-c60efe80-dd7e-11e9-8179-bc028c5fa398.png)

Then i get this message

![Captura de pantalla de 2019-09-22 21-17-43](https://user-images.githubusercontent.com/13435862/65393248-bee7f080-dd7e-11e9-8e3a-b963c03ed75e.png)

Later if i reboot nodered, deconz-server node disapear from nodes list and is not selectable anymore for the rest of deconz nodes

I'll ve happy to give more info if is in my hands

### Hardware / Software

- raspberry 3A+  
- nodered 0.20.7
- version of deconz gateway:  2.05.60 / 10/3/2019
- version of node-red-contrib-deconz: [0.13]

**Comment by andreypopov** [comment]
what is nodejs version in docker?

**Comment by Parufito** [comment]
I'm using node-red-docker:rpi-v8 docker image, so i supose that it has nodered v8

**Comment by andreypopov** [comment]
you have to update to 10x+

**Comment by Parufito** [comment]
Thanks! Not sure if it's possible yet on raspberry. I'll wait for a v10 docker version

Thanks again and good job with this nodes!

**Comment by Parufito** [comment]
I've got nodered with node v10 on Raspberry and it works! Thanks!
