### ISSUE TITLE
Correct format of Switch(true/false)

### ISSUE THREAD

**Issue by ronsmits** [andreypopov/node-red-contrib-deconz#34]
I wanted to setup a Deconz-out node switching a light off. if switch the payload to "string" and put in true, it will switch the light on. But if I put in false it does not switch it off. If I put the payload to number and put in 0 it will switch it off.

What is the correct way of doing it?

**Comment by acidmad** [comment]
+1

**Comment by andreypopov** [comment]
show me your OUT node

**it can accept 1/0 or true/false !** 

![2019-10-11_17-56-51](https://user-images.githubusercontent.com/1624839/66661941-8e45f900-ec50-11e9-9f2b-87166a0acfa9.png)

**Comment by andreypopov** [comment]
or you can 
![2019-10-11_17-58-30](https://user-images.githubusercontent.com/1624839/66662056-c4837880-ec50-11e9-80bb-c97887894971.png)

or  the same

![2019-10-11_17-59-48](https://user-images.githubusercontent.com/1624839/66662145-f0066300-ec50-11e9-95d6-02d111f26f56.png)
