### ISSUE TITLE
Magic button is not visible on server properties

### ISSUE THREAD

**Issue by lancusfpv** [andreypopov/node-red-contrib-deconz#36]
** Describe issue **
Magic button is not visible on server properties only "Get Settings" text. I am using it on node-red in hassio that runs on a rpi3B. I am unable to add server setting to initiate the api key request.

** Your flow here **
No flow yet. I am trying to connect to deconz gatway on 

** Screens / Logs **

![image](https://user-images.githubusercontent.com/39004272/66945863-0eed6680-f050-11e9-89f5-550db51238b7.png)

** Hardware / Software **
  - raspberry 3  B
  - version of deconz gateway: [2.05.69 / 9/6/2019] 
  - version of node-red-contrib-deconz: [1.0.4]
- node-red version: 4.2.1
- hassio version: 0.98.2.

**Comment by andreypopov** [comment]
use manual settings , there are many possibilities why it doesnt work

**Comment by lancusfpv** [comment]
How can I manually request API key from deconz gatway?

**Comment by andreypopov** [comment]
Read node's info, there is LINK to manual.

**Comment by andreypopov** [comment]
What kind of error do your receive?

**Comment by lancusfpv** [comment]
no error, I am following this guide: https://www.youtube.com/watch?v=i3TiZiuNofM
and no magic button like in the video at 0:19

**Comment by andreypopov** [comment]
you use old version of node-red. it is okay, link instead of button
install latest stable node-red

**Comment by lancusfpv** [comment]
I am using the latest 4.2.1 node-red

**Comment by andreypopov** [comment]
https://nodered.org/ 1.0.2 is the latest version

**Comment by lancusfpv** [comment]
i am using nodered addon in hassio. 
https://github.com/hassio-addons/addon-node-red/releases

**Comment by andreypopov** [comment]
did u find magick btn ? node red version under 1.0
![2019-10-29_09-54-23](https://user-images.githubusercontent.com/1624839/67744279-1e968300-fa32-11e9-87a5-4381f0ac6241.png)

in node-red 1.0+ it looks like
![2019-10-29_09-55-59](https://user-images.githubusercontent.com/1624839/67744368-58678980-fa32-11e9-854b-251f3cdad7df.png)
