### ISSUE TITLE
Develist empty after update to 1.1.0

### ISSUE THREAD

**Issue by vandalon** [andreypopov/node-red-contrib-deconz#39]
** Describe issue **
After updating to 1.1.0 the devicelist is empty on existing nodes as well as in new nodes, no error. 
Seems a cosmetic issue because everything still works as configured. 
Issue appears in in/get/out nodes.

** Hardware / Software **
  - raspberry 4   
  - version of deconz gateway: [2.05.69] 
  - version of node-red-contrib-deconz: [1.1.0]

**Comment by vandalon** [comment]
Ok, reason is simple: multiple-select.min.js is missing :)

**Comment by EspenHalvorsen** [comment]
Same issue. Refresh Devices List not working

**Comment by bohtho** [comment]
Same issue, rpi3, deconz 2.05.69.

**Comment by andreypopov** [comment]
> Ok, reason is simple: multiple-select.min.js is missing but referred to in deconz.html

thanks! uploaded v1.1.2

**Comment by MattL0** [comment]
Cn anybody confirm 1.1.2 is ok? I had to load a ssd backup to return to my old 5 days )system

**Comment by markus-fischbacher** [comment]
I‘m using version 1.1.10 and my device list is empty. Using HA with RaspBee and deConz Add-on. Any ideas?

**Comment by andreypopov** [comment]
> I‘m using version 1.1.10 and my device list is empty. Using HA with RaspBee and deConz Add-on. Any ideas?

did you make deploy?

**Comment by markus-fischbacher** [comment]
Yes, of course.

**Comment by andreypopov** [comment]
> Yes, of course.

show me your config

**Comment by markus-fischbacher** [comment]
![AB145924-1714-43B3-B67F-4D1B667960E9](https://user-images.githubusercontent.com/10846308/73606954-62100880-45b0-11ea-8738-cb5f34a9cff7.png)
![CC3B3614-4451-4CCE-BE08-86A84E459682](https://user-images.githubusercontent.com/10846308/73606955-62100880-45b0-11ea-8e0e-829391b6078a.png)
![7704BAEC-0F8F-47AE-8570-D25C5AA0B436](https://user-images.githubusercontent.com/10846308/73606956-62a89f00-45b0-11ea-9be0-d8dca832618e.png)

**Comment by markus-fischbacher** [comment]
Doesn‘t matter, got the values from HA nodes. 
Thanks for your support.

**Comment by fhbweber** [comment]
I'm using version 1.1.13 on an raspi 4 node-red 0.20.8 no HA !!! 
The deviceList is not shown in either node. Without a deviceList to select something this node is useless.
I tested the ConBee Gateway with RestApi Client , all O.K.
Please make it work. Thanks in advance.

**Comment by andreypopov** [comment]
upgrade node-red to 1.0.4 please
I dont support old versions anymore

**Comment by fhbweber** [comment]
Sorry, I just tested it on my other system, Raspi 3, node-red v0.19.6 and it worked !!!
The only difference is that the workspace language on this system is english and on the not working system is german.
<img width="502" alt="Bildschirmfoto 2020-03-12 um 12 07 34" src="https://user-images.githubusercontent.com/47576945/76516186-44f61180-645b-11ea-9783-aa1b971ee607.png">
<img width="500" alt="Bildschirmfoto 2020-03-12 um 12 08 02" src="https://user-images.githubusercontent.com/47576945/76516212-4a535c00-645b-11ea-8b43-c079d7bc0634.png">

**Comment by andreypopov** [comment]
0.19 is too old.

**Comment by fhbweber** [comment]
O.K. I updated everything to newest version. See attached screenshot.
I also changed locale to us english. The problem - empty device list still existst.
Then I exported the working node from my older system and imported the node, deployed it and it worked.  But refreshing the device list still doesn't work, the list is empty.
<img width="742" alt="Bildschirmfoto 2020-03-12 um 21 05 39" src="https://user-images.githubusercontent.com/47576945/76562802-6cbe9700-64a6-11ea-8e99-6ad03acf1acd.png">

**Comment by andreypopov** [comment]
try to open url like (but insert your data)
http://192.168.1.20:40850/api/23B803325F  what is the result?

**Comment by fhbweber** [comment]
Hi Andrey, I opened this url in postman from chrome browser:
http://192.168.0.195:8080/api/16BF6AEABD and got following result
{
    "config": {
        "UTC": "2020-03-13T08:58:42",
        "apiversion": "1.16.0",
        "backup": {
            "errorcode": 0,
            "status": "idle"
        },
        "bridgeid": "00212EFFFF032604",
        "datastoreversion": "60",
        "devicename": "ConBee",
        "dhcp": true,
        "factorynew": false,
        "fwversion": "0x26330500",
        "gateway": "192.168.0.1",
        "internetservices": {
            "remoteaccess": "disconnected"
        },
        "ipaddress": "192.168.0.195",
        "linkbutton": false,
        "localtime": "2020-03-13T09:58:42",
        "mac": "dc:a6:32:30:b9:f3",
        "modelid": "deCONZ",
        "name": "Phoscon-GW",
        "netmask": "255.255.255.0",
        "networkopenduration": 60,
        "panid": 17539,
        "portalconnection": "disconnected",
        "portalservices": false,
        "portalstate": {
            "communication": "disconnected",
            "incoming": false,
            "outgoing": false,
            "signedon": false
        },
        "proxyaddress": "none",
        "proxyport": 0,
        "replacesbridgeid": null,
        "rfconnected": true,
        "starterkitid": "",
        "swupdate": {
            "checkforupdate": false,
            "devicetypes": {
                "bridge": false,
                "lights": [],
                "sensors": []
            },
            "notify": false,
            "text": "",
            "updatestate": 0,
            "url": ""
        },
        "swupdate2": {
            "autoinstall": {
                "on": false,
                "updatetime": ""
            },
            "bridge": {
                "lastinstall": "2020-02-25T12:46:04",
                "state": "allreadytoinstall"
            },
            "checkforupdate": false,
            "install": false,
            "lastchange": "",
            "lastinstall": "",
            "state": "allreadytoinstall"
        },
        "swversion": "2.5.74",
        "timeformat": "24h",
        "timezone": "Europe/Berlin",
        "uuid": "bb6a9e61-7b11-4896-a41d-40515785f496",
        "websocketnotifyall": true,
        "websocketport": 443,
        "whitelist": {
            "111B0777C6": {
                "create date": "2020-03-10T15:17:30",
                "last use date": "2020-03-12T17:55:19",
                "name": "Phoscon#B2061x1026"
            },
            "1503E087A4": {
                "create date": "2020-03-10T11:07:18",
                "last use date": "2020-03-12T21:07:28",
                "name": "Phoscon#B1308x782"
            },
            "16BF6AEABD": {
                "create date": "2020-03-10T15:25:37",
                "last use date": "2020-03-13T08:58:42",
                "name": "Node-red"
            },
            "2CE91D6930": {
                "create date": "2020-03-10T15:19:53",
                "last use date": "2020-03-10T16:45:35",
                "name": "deCONZ WebApp"
            },
            "3C327B39B7": {
                "create date": "2020-03-10T19:12:57",
                "last use date": "2020-03-10T19:14:01",
                "name": "deCONZ WebApp"
            },
            "4133D999C4": {
                "create date": "2020-03-10T11:33:57",
                "last use date": "2020-03-10T15:25:53",
                "name": "Node-red"
            },
            "528A7EF596": {
                "create date": "2020-03-10T11:29:15",
                "last use date": "2020-03-10T11:29:15",
                "name": "my application"
            },
            "6C64FE0F7D": {
                "create date": "2020-03-10T11:11:56",
                "last use date": "2020-03-10T11:16:03",
                "name": "deCONZ WebApp"
            },
            "7383AEEF21": {
                "create date": "2020-03-10T11:32:06",
                "last use date": "2020-03-10T11:33:30",
                "name": "Node-red"
            },
            "79BEF4AA6A": {
                "create date": "2020-03-10T11:28:10",
                "last use date": "2020-03-10T14:59:18",
                "name": "deCONZ WebApp"
            },
            "7FB0D1896B": {
                "create date": "2020-03-10T15:03:01",
                "last use date": "2020-03-10T15:04:26",
                "name": "my application"
            },
            "836370633F": {
                "create date": "2020-03-10T14:00:52",
                "last use date": "2020-03-10T14:20:34",
                "name": "Phoscon#B414x719"
            },
            "84F798A73E": {
                "create date": "2020-03-07T15:41:13",
                "last use date": "2020-03-07T16:40:36",
                "name": "Phoscon#B1022x630"
            },
            "8C68E29343": {
                "create date": "2020-03-07T16:40:50",
                "last use date": "2020-03-07T16:41:59",
                "name": "Phoscon#B2061x1090"
            },
            "93C230E27A": {
                "create date": "2020-03-10T11:16:43",
                "last use date": "2020-03-10T11:31:14",
                "name": "my application"
            },
            "AB34A49D75": {
                "create date": "2020-03-12T21:04:57",
                "last use date": "2020-03-12T21:07:27",
                "name": "deCONZ WebApp"
            },
            "D954F0F501": {
                "create date": "2020-03-07T16:36:42",
                "last use date": "2020-03-07T16:38:56",
                "name": "deCONZ WebApp"
            },
            "DD64E40FFC": {
                "create date": "2020-03-10T11:20:08",
                "last use date": "2020-03-10T11:20:33",
                "name": "my application"
            },
            "F22364914F": {
                "create date": "2020-03-10T11:33:09",
                "last use date": "2020-03-10T11:34:03",
                "name": "Node-red"
            },
            "F2CBAB8497": {
                "create date": "2020-03-10T11:29:54",
                "last use date": "2020-03-10T15:01:21",
                "name": "my application"
            },
            "FE0F7D7023": {
                "create date": "2020-03-10T10:58:37",
                "last use date": "2020-03-10T11:02:22",
                "name": "deCONZ WebApp"
            },
            "FEAB631372": {
                "create date": "2020-03-10T11:28:39",
                "last use date": "2020-03-10T11:29:02",
                "name": "my application"
            }
        },
        "zigbeechannel": 15
    },
    "groups": {
        "2": {
            "action": {
                "bri": 128,
                "colormode": "hs",
                "ct": 0,
                "effect": "none",
                "hue": 0,
                "on": false,
                "sat": 128,
                "scene": null,
                "xy": [
                    0,
                    0
                ]
            },
            "devicemembership": [],
            "etag": "4e3ca40736c01ffcc1ccdbf7fd4bdbd2",
            "id": "2",
            "lights": [
                "2"
            ],
            "name": "Lichter",
            "scenes": [],
            "state": {
                "all_on": false,
                "any_on": false
            },
            "type": "LightGroup"
        },
        "240": {
            "action": {
                "bri": 127,
                "colormode": "hs",
                "ct": 0,
                "effect": "none",
                "hue": 0,
                "on": false,
                "sat": 127,
                "scene": null,
                "xy": [
                    0,
                    0
                ]
            },
            "devicemembership": [],
            "etag": "cccb348bf0dfdbc1b2a252418a2e5cdf",
            "id": "240",
            "lights": [
                "3"
            ],
            "name": "Arbeitszimmer",
            "scenes": [],
            "state": {
                "all_on": false,
                "any_on": false
            },
            "type": "LightGroup"
        }
    },
    "lights": {
        "1": {
            "etag": "3a20cbf3666b756d30bc122138d5967a",
            "hascolor": false,
            "manufacturername": "dresden elektronik",
            "modelid": "ConBee",
            "name": "ConBee",
            "state": {
                "alert": "none",
                "on": true,
                "reachable": true
            },
            "swversion": "0x26330500",
            "type": "Unknown",
            "uniqueid": "00:21:2e:ff:ff:03:26:04-01"
        },
        "2": {
            "ctmax": 555,
            "ctmin": 153,
            "etag": "4e3ca40736c01ffcc1ccdbf7fd4bdbd2",
            "hascolor": true,
            "manufacturername": "MLI",
            "modelid": "ZBT-ExtendedColor",
            "name": "Extended color light 2",
            "state": {
                "alert": "none",
                "bri": 122,
                "colormode": "xy",
                "ct": 273,
                "effect": "none",
                "hue": 0,
                "on": false,
                "reachable": true,
                "sat": 254,
                "xy": [
                    0.3995,
                    0.1723
                ]
            },
            "swversion": "2.2",
            "type": "Extended color light",
            "uniqueid": "00:0d:6f:ff:fe:1b:b2:42-01"
        },
        "3": {
            "ctmax": 370,
            "ctmin": 153,
            "etag": "cccb348bf0dfdbc1b2a252418a2e5cdf",
            "hascolor": true,
            "manufacturername": "MLI",
            "modelid": "ZBT-ColorTemperature",
            "name": "Color temperature light 3",
            "state": {
                "alert": "none",
                "bri": 183,
                "colormode": "ct",
                "ct": 370,
                "on": false,
                "reachable": true
            },
            "swversion": "2.0",
            "type": "Color temperature light",
            "uniqueid": "00:15:8d:00:03:1d:80:a7-01"
        }
    },
    "resourcelinks": {},
    "rules": {},
    "scenes": {},
    "schedules": {},
    "sensors": {
        "1": {
            "config": {
                "configured": true,
                "on": true,
                "sunriseoffset": 30,
                "sunsetoffset": -30
            },
            "etag": "0f8c7a88d4b04b375195f6a9da4d835c",
            "manufacturername": "Philips",
            "modelid": "PHDL00",
            "name": "Daylight",
            "state": {
                "dark": false,
                "daylight": true,
                "lastupdated": "2020-03-13T06:23:21",
                "status": 160,
                "sunrise": "2020-03-13T05:38:58",
                "sunset": "2020-03-13T17:21:45"
            },
            "swversion": "1.0",
            "type": "Daylight",
            "uniqueid": "00:21:2e:ff:ff:03:26:04-01"
        }
    }
}

**Comment by fhbweber** [comment]
Or do you prefer this non beautified output?
{"config":{"UTC":"2020-03-14T20:16:46","apiversion":"1.16.0","backup":{"errorcode":0,"status":"idle"},"bridgeid":"00212EFFFF032604","datastoreversion":"60","devicename":"ConBee","dhcp":true,"factorynew":false,"fwversion":"0x26330500","gateway":"192.168.0.1","internetservices":{"remoteaccess":"disconnected"},"ipaddress":"192.168.0.195","linkbutton":false,"localtime":"2020-03-14T21:16:46","mac":"dc:a6:32:30:b9:f3","modelid":"deCONZ","name":"Phoscon-GW","netmask":"255.255.255.0","networkopenduration":60,"panid":17539,"portalconnection":"disconnected","portalservices":false,"portalstate":{"communication":"disconnected","incoming":false,"outgoing":false,"signedon":false},"proxyaddress":"none","proxyport":0,"replacesbridgeid":null,"rfconnected":true,"starterkitid":"","swupdate":{"checkforupdate":false,"devicetypes":{"bridge":false,"lights":[],"sensors":[]},"notify":false,"text":"","updatestate":0,"url":""},"swupdate2":{"autoinstall":{"on":false,"updatetime":""},"bridge":{"lastinstall":"2020-02-25T12:46:04","state":"allreadytoinstall"},"checkforupdate":false,"install":false,"lastchange":"","lastinstall":"","state":"allreadytoinstall"},"swversion":"2.5.74","timeformat":"24h","timezone":"Europe/Berlin","uuid":"bb6a9e61-7b11-4896-a41d-40515785f496","websocketnotifyall":true,"websocketport":443,"whitelist":{"111B0777C6":{"create date":"2020-03-10T15:17:30","last use date":"2020-03-12T17:55:19","name":"Phoscon#B2061x1026"},"1503E087A4":{"create date":"2020-03-10T11:07:18","last use date":"2020-03-13T14:55:20","name":"Phoscon#B1308x782"},"16BF6AEABD":{"create date":"2020-03-10T15:25:37","last use date":"2020-03-14T20:16:46","name":"Node-red"},"2CE91D6930":{"create date":"2020-03-10T15:19:53","last use date":"2020-03-10T16:45:35","name":"deCONZ WebApp"},"3C327B39B7":{"create date":"2020-03-10T19:12:57","last use date":"2020-03-10T19:14:01","name":"deCONZ WebApp"},"4133D999C4":{"create date":"2020-03-10T11:33:57","last use date":"2020-03-10T15:25:53","name":"Node-red"},"528A7EF596":{"create date":"2020-03-10T11:29:15","last use date":"2020-03-10T11:29:15","name":"my application"},"6C64FE0F7D":{"create date":"2020-03-10T11:11:56","last use date":"2020-03-10T11:16:03","name":"deCONZ WebApp"},"7383AEEF21":{"create date":"2020-03-10T11:32:06","last use date":"2020-03-10T11:33:30","name":"Node-red"},"79BEF4AA6A":{"create date":"2020-03-10T11:28:10","last use date":"2020-03-10T14:59:18","name":"deCONZ WebApp"},"7FB0D1896B":{"create date":"2020-03-10T15:03:01","last use date":"2020-03-10T15:04:26","name":"my application"},"836370633F":{"create date":"2020-03-10T14:00:52","last use date":"2020-03-10T14:20:34","name":"Phoscon#B414x719"},"84F798A73E":{"create date":"2020-03-07T15:41:13","last use date":"2020-03-07T16:40:36","name":"Phoscon#B1022x630"},"8C68E29343":{"create date":"2020-03-07T16:40:50","last use date":"2020-03-07T16:41:59","name":"Phoscon#B2061x1090"},"93C230E27A":{"create date":"2020-03-10T11:16:43","last use date":"2020-03-10T11:31:14","name":"my application"},"AB34A49D75":{"create date":"2020-03-12T21:04:57","last use date":"2020-03-12T21:07:27","name":"deCONZ WebApp"},"CFE4618457":{"create date":"2020-03-13T14:55:44","last use date":"2020-03-13T14:55:49","name":"deCONZ WebApp"},"D954F0F501":{"create date":"2020-03-07T16:36:42","last use date":"2020-03-07T16:38:56","name":"deCONZ WebApp"},"DD64E40FFC":{"create date":"2020-03-10T11:20:08","last use date":"2020-03-10T11:20:33","name":"my application"},"F22364914F":{"create date":"2020-03-10T11:33:09","last use date":"2020-03-10T11:34:03","name":"Node-red"},"F2CBAB8497":{"create date":"2020-03-10T11:29:54","last use date":"2020-03-10T15:01:21","name":"my application"},"FE0F7D7023":{"create date":"2020-03-10T10:58:37","last use date":"2020-03-10T11:02:22","name":"deCONZ WebApp"},"FEAB631372":{"create date":"2020-03-10T11:28:39","last use date":"2020-03-10T11:29:02","name":"my application"}},"zigbeechannel":15},"groups":{"2":{"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"etag":"cbfa358b0cff8451ecc58f36b2aba2f1","id":"2","lights":["2"],"name":"Lichter","scenes":[],"state":{"all_on":true,"any_on":true},"type":"LightGroup"},"240":{"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"etag":"27f0328edd2a6893ef3cf2a054216898","id":"240","lights":["3"],"name":"Arbeitszimmer","scenes":[],"state":{"all_on":true,"any_on":true},"type":"LightGroup"}},"lights":{"1":{"etag":"bee78a2929ed1d1d39fffe6f189edd51","hascolor":false,"manufacturername":"dresden elektronik","modelid":"ConBee","name":"ConBee","state":{"alert":"none","on":true,"reachable":true},"swversion":"0x26330500","type":"Unknown","uniqueid":"00:21:2e:ff:ff:03:26:04-01"},"2":{"ctmax":555,"ctmin":153,"etag":"cbfa358b0cff8451ecc58f36b2aba2f1","hascolor":true,"manufacturername":"MLI","modelid":"ZBT-ExtendedColor","name":"Extended color light 2","state":{"alert":"none","bri":122,"colormode":"xy","ct":273,"effect":"none","hue":0,"on":true,"reachable":true,"sat":254,"xy":[0.3995,0.1723]},"swversion":"2.2","type":"Extended color light","uniqueid":"00:0d:6f:ff:fe:1b:b2:42-01"},"3":{"ctmax":370,"ctmin":153,"etag":"27f0328edd2a6893ef3cf2a054216898","hascolor":true,"manufacturername":"MLI","modelid":"ZBT-ColorTemperature","name":"Color temperature light 3","state":{"alert":"none","bri":183,"colormode":"ct","ct":370,"on":true,"reachable":true},"swversion":"2.0","type":"Color temperature light","uniqueid":"00:15:8d:00:03:1d:80:a7-01"}},"resourcelinks":{},"rules":{},"scenes":{},"schedules":{},"sensors":{"1":{"config":{"configured":true,"on":true,"sunriseoffset":30,"sunsetoffset":-30},"etag":"3e9dc381fec17a764842fc4b9aa3f9e6","manufacturername":"Philips","modelid":"PHDL00","name":"Daylight","state":{"dark":true,"daylight":false,"lastupdated":"2020-03-14T19:15:38","status":230,"sunrise":"2020-03-14T05:36:42","sunset":"2020-03-14T17:23:27"},"swversion":"1.0","type":"Daylight","uniqueid":"00:21:2e:ff:ff:03:26:04-01"}}}

**Comment by hvddrift** [comment]
I have the same issue. I can detect events but I am unable to populate the device list.
