### ISSUE TITLE
ACK or command confirmation

### ISSUE THREAD

**Issue by arozhankov** [andreypopov/node-red-contrib-deconz#4]
Hello.

I met the lack of action of the device after sending the command to this device.

The motion sensor has created a command to turn on the light switch. The log describes that the sensor has triggered + a command has been sent to the switch + the switch status has been changed to "on". However, the device is not physically turned on.

It turned on only after I changed the status to "off" and then to "on".

Is it possible to implement a device status change check after sending a command? (ACK?)

**Comment by andreypopov** [comment]
Please, provide your flow here.

**Comment by arozhankov** [comment]
`[
    {
        "id": "fd3c838b.0214a",
        "type": "tab",
        "label": "Test",
        "disabled": false,
        "info": ""
    },
    {
        "id": "d516bb6f.87eb18",
        "type": "deconz-output",
        "z": "fd3c838b.0214a",
        "name": "",
        "server": "c033efbd.4e1d",
        "device": "00:15:8d:00:01:f3:f8:4d-03",
        "device_name": "Bathroom Main : Smart plug",
        "command": "on",
        "commandType": "deconz_cmd",
        "payload": "payload",
        "payloadType": "msg",
        "x": 1280,
        "y": 460,
        "wires": []
    },
    {
        "id": "7111036d.b43a9c",
        "type": "deconz-input",
        "z": "fd3c838b.0214a",
        "name": "",
        "server": "c033efbd.4e1d",
        "device": "00:15:8d:00:03:05:8d:9d-01-0406",
        "device_name": "Bathroom Motion : ZHAPresence",
        "state": "presence",
        "outputAtStartup": true,
        "x": 810,
        "y": 460,
        "wires": [
            [
                "bc4fc5bf.dac268",
                "bc57d1d9.3d7e8"
            ],
            []
        ]
    },
    {
        "id": "bc4fc5bf.dac268",
        "type": "debug",
        "z": "fd3c838b.0214a",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "x": 1070,
        "y": 400,
        "wires": []
    },
    {
        "id": "bc57d1d9.3d7e8",
        "type": "switch",
        "z": "fd3c838b.0214a",
        "name": "Motion?",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "true"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 1,
        "x": 1060,
        "y": 460,
        "wires": [
            [
                "d516bb6f.87eb18"
            ]
        ]
    },
    {
        "id": "4746cac0.e9ef24",
        "type": "deconz-input",
        "z": "fd3c838b.0214a",
        "name": "",
        "server": "c033efbd.4e1d",
        "device": "00:15:8d:00:01:f3:f8:4d-03",
        "device_name": "Bathroom Main : Smart plug",
        "state": "on",
        "outputAtStartup": true,
        "x": 820,
        "y": 620,
        "wires": [
            [
                "e343a4d7.b63c78"
            ],
            []
        ]
    },
    {
        "id": "e343a4d7.b63c78",
        "type": "debug",
        "z": "fd3c838b.0214a",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "x": 1070,
        "y": 620,
        "wires": []
    },
    {
        "id": "c033efbd.4e1d",
        "type": "deconz-server",
        "z": "",
        "name": "Conbee2-AR",
        "ip": "10.0.1.100",
        "port": "8080",
        "apikey": "C0F72B7881",
        "ws_port": "8088"
    }
]`

**Comment by andreypopov** [comment]
I have aqara bulb and there were several issues:
after starting deconz service, REST API does not return bulb at all. It will appear only in 20 seconds but it still will not work. After ~60-80 seconds more: will work only on/off function. Full initialization takes 3-5 minutes! 

So, start deconz, wait 10 minutes, try this flow on version 0.10 !

**Comment by arozhankov** [comment]
May be... My service usually has 4-7 days uptime.
