### ISSUE TITLE
Scenes selected by deCONZ have the wrong value

### ISSUE THREAD

**Issue by MrMiracles** [andreypopov/node-red-contrib-deconz#40]
Just tried the new scenes option (version 1.1.3). While selecting a scene from the drop-down list it seems like the scenes get the wrong value with the name. The first scene in the list has the value "0", which is impossible because scenes start counting from 1. I think (not sure) that the value is actually the array ID instead of the scene id. Thanks for the good work on this anyway! 

For others who have the some problem:
It's an easy fix, just use the number field and manually add the scene ID there.

![image](https://user-images.githubusercontent.com/56234178/68075763-a2db6400-fdac-11e9-969a-22e4d8327cbd.png)

![image](https://user-images.githubusercontent.com/56234178/68075770-ae2e8f80-fdac-11e9-92b3-25c76a6fbc94.png)

**Comment by andreypopov** [comment]
thank you, fixed in 
node-red-contrib-deconz@1.1.4
