### ISSUE TITLE
API Key not discoverable

### ISSUE THREAD

**Issue by nicedevil007** [andreypopov/node-red-contrib-deconz#41]
Hey guys,

I'm using your node and can't get any API Key from my conbee 2.

All of my IoT things are running on a raspberry pi 4 in a docker environment.

All of them got a separate created network and only the devices that should see each other are connected between those virtual networks.

F.e. my nodered got the network "nodered" and my deconz container got the "deconz" network.
Both containers are joined to the nodered and deconz network so traffic between them should be easy.

I changed the environment variable from 80 to 8083 and 443 to 10443 f.e.

This ports are used at the docker run command like -p 8083:8083 and -p 10443:10443 because you wrote that is a known issue (we have to have both ends with same ports and same environment variable set).

but still, it can't find any api key :(

here is a screen of my example (testet with ssl and without) / deconz is the hostname, also tested with 127.0.0.1

![image](https://user-images.githubusercontent.com/17103076/68330484-a5eb9280-00d3-11ea-8d6f-bf5603e47334.png)

**Comment by andreypopov** [comment]
try to get key manually
https://dresden-elektronik.github.io/deconz-rest-doc/authorization/

**Comment by nicedevil007** [comment]
was able to fix this with switching from bridge to host network

**Comment by nicedevil007** [comment]
today I had to install a new instance of node-red, starting from scratch.

The Conbee stick is the same I used before. Now I'm not able to get it connected to any of my devices.

I did the manual way and I get an error

![image](https://user-images.githubusercontent.com/17103076/70867876-bcaac200-1f7a-11ea-92d8-2c7776bd015f.png)

**Comment by nicedevil007** [comment]
Got it by trying more and more times... while I tested so much possible settings with my docker network, I didn't know for sure what was the solution :(
