### ISSUE TITLE
Can you give us an Example for Philips Hue RGB LED Bulb with Dashboard Colorpicker?

### ISSUE THREAD

**Issue by nicedevil007** [andreypopov/node-red-contrib-deconz#43]
Hey guys,

first, I want to thank you all for your work! Everything works like a charm :)

Today I got my first RGB LED Bulbs from Philips. First I tryed to set the brightness, everything works like on normal Philips Spots. Then I tryed to change the color with the Dashboard Colorpicker.
That is a bit confusing for me :(

Your Lightnode puts out realy much variables. That I don't know how to translate or recalculate them :( 

The RGB Colorpicker puts out a Color in rgb style or hex. But if I input a color with hex the color mode changes by itself to hs instead of xy.

Would be realy nice to know how which variable should be used here <3 Thank you in advance.

**Comment by andreypopov** [comment]
Hi, you have to convert HSL color from deconz to RGB/HEX
try to use https://flows.nodered.org/node/node-red-contrib-color-convert

**Comment by nicedevil007** [comment]
Can u tell me which value of the deconz output is which variable of the HSL object?
Will try out this evening <3

**Comment by andreypopov** [comment]
You can use second output, values are formatted for homekit, but they converted 
Or you can convert like here:

Deconz Hue 65535  is 360 
![2019-10-10_10-21-38](https://user-images.githubusercontent.com/1624839/69608815-3b29d900-1039-11ea-8ee4-d9ad84e16598.png)

**Comment by nicedevil007** [comment]
Thank you! THAT was what I'm looking for <3
Dunno why, but all those node-red devs are fast as rocket and deliver solutions that are simple as... :D

Will report back this evening.

**Comment by nicedevil007** [comment]
Runs perfect!

Could I make an enhancement request in this issue as well? :)

Could you add the ability to use objects for the new values of hue/sat and so on?

![image](https://user-images.githubusercontent.com/17103076/69671322-16178380-1096-11ea-8418-01602ea08c70.png)

Instead of forcing us to use msg.xyz => msg.payload.xyz (f.e. msg.payload.hue)

**Comment by andreypopov** [comment]
![2019-10-10_10-21-38](https://user-images.githubusercontent.com/1624839/69671453-1ec48580-10a7-11ea-99f0-7cbb5699370e.png)

??

**Comment by andreypopov** [comment]
and yes, you can use "msg.hue" too

**Comment by nicedevil007** [comment]
ah ok, will try that.

will that work with colormode as well? tryed to send msg.payload.colormode = hue to that node and didn't work.

![image](https://user-images.githubusercontent.com/17103076/69760771-ad97d780-1165-11ea-869d-d9846cc64a1c.png)

**Comment by andreypopov** [comment]
https://dresden-elektronik.github.io/deconz-rest-doc/lights/
![2019-11-28_10-02-32](https://user-images.githubusercontent.com/1624839/69784171-3cd4d780-11c6-11ea-89e4-8ea5c182b0e3.png)

**Comment by nicedevil007** [comment]
woot perfect man! everything is clear now :)
