### ISSUE TITLE
zigbee2mqtt support

### ISSUE THREAD

**Issue by osos** [andreypopov/node-red-contrib-deconz#44]
Currently use these great nodes with deCONZ.

Have also been using zigbee2mqtt. Now considering that again.

I think this node could be made a hybrid for both zigbee2mqtt and deCONZ users. Basically I would think that by "simply" amending the server-node to understand and connect with zigbee2mqtt could accomplish this.

Please consider.

**Comment by osos** [comment]
Zigbee2mqtt is about to get ConBee support. https://github.com/Koenkk/zigbee-herdsman/issues/72
Great the two are working together. Another reason to join efforts in your great node-red contrib

**Comment by bohtho** [comment]
There’s a node-red-contrib-zigbee that includes zigbee-herdsman (the same core as zigbee2mqtt). It’s not currently compatible with a Conbee though.

**Comment by andreypopov** [comment]
this lib is working only with deconz API
