### ISSUE TITLE
DeConz no data coming from Phoscon app/REST API

### ISSUE THREAD

**Issue by elpaso666** [andreypopov/node-red-contrib-deconz#48]
** Describe issue **
I am having an Xiaomy Temperature sensor fully paired with Phoscon App and I am getting updates on any humi/temperature change in Phoscon app.

How ever NodeRed IN gets update only when I deploy the flow, I see disconnected and then correct value appears, but automatic update on change is not happening.

** Your flow here **
not needed, only DeconzIN is in place with Phoscon APP connection and API key (which is working correctly, as after flow deploy I get correct data 

** Screens / Logs **

** Hardware / Software **
  - raspberry 3   
  - version of deconz gateway: [2.05.71] 
  - version of node-red-contrib-deconz: [1.1.9]

**Comment by elpaso666** [comment]
I just found out, that debug in NodeRed is saying:

"WebSocket error: Error: WebSocket was closed before the connection was established"

Also I have added a Xiaomi button, which is detected again, but no data coming from Phoscon. Is it realted to closed WebSocket from NodeRed towards Phoscon REST API?

**Comment by andreypopov** [comment]
something is wrong with websocket connection

I use rest API for flow start and polling every X seconds
websocket is for instant changes, check your settings, possible port is closed!

**Comment by elpaso666** [comment]
Hi,

I have installed the deconz/NodeRed on same RPI as the Phoscon and now everything works as expected.

thx for GOOD JOB!
