### ISSUE TITLE
NodeRed Reboot

### ISSUE THREAD

**Issue by Schmello** [andreypopov/node-red-contrib-deconz#49]
Sometimes Node Red restarts.
I can't say exactly where it comes from.
Here is an excerpt from the log file

`Dec 26 16:48:08 Homematic daemon.err node-red: 26 Dec 16:48:08 - [red] Uncaught Exception:
Dec 26 16:48:08 Homematic daemon.err node-red: 26 Dec 16:48:08 - TypeError: Cannot read property 'devices' of null
Dec 26 16:48:08 Homematic daemon.err node-red:     at ServerNode.onSocketMessage (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-deconz/nodes/server.js:237:37)
Dec 26 16:48:08 Homematic daemon.err node-red:     at DeconzSocket.ServerNode.node.socket.on (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-deconz/nodes/server.js:34:57)
Dec 26 16:48:08 Homematic daemon.err node-red:     at DeconzSocket.emit (events.js:198:13)
Dec 26 16:48:08 Homematic daemon.err node-red:     at DeconzSocket.EventEmitter.emit (domain.js:448:20)
Dec 26 16:48:08 Homematic daemon.err node-red:     at DeconzSocket.onMessage (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-deconz/lib/deconz-socket.js:137:18)
Dec 26 16:48:08 Homematic daemon.err node-red:     at WebSocket.socket.on.data (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-deconz/lib/deconz-socket.js:59:48)
Dec 26 16:48:08 Homematic daemon.err node-red:     at WebSocket.emit (events.js:198:13)
Dec 26 16:48:08 Homematic daemon.err node-red:     at WebSocket.EventEmitter.emit (domain.js:448:20)
Dec 26 16:48:08 Homematic daemon.err node-red:     at Receiver.receiverOnMessage (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-deconz/node_modules/ws/lib/websocket.js:800:20)
Dec 26 16:48:08 Homematic daemon.err node-red:     at Receiver.emit (events.js:198:13)
Dec 26 16:48:08 Homematic daemon.err node-red:     at Receiver.EventEmitter.emit (domain.js:448:20)
Dec 26 16:48:08 Homematic daemon.err node-red:     at Receiver.dataMessage (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-deconz/node_modules/ws/lib/receiver.js:423:14)
Dec 26 16:48:08 Homematic daemon.err node-red:     at Receiver.getData (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-deconz/node_modules/ws/lib/receiver.js:353:17)
Dec 26 16:48:08 Homematic daemon.err node-red:     at Receiver.startLoop (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-deconz/node_modules/ws/lib/receiver.js:139:22)
Dec 26 16:48:08 Homematic daemon.err node-red:     at Receiver._write (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-deconz/node_modules/ws/lib/receiver.js:74:10)
Dec 26 16:48:08 Homematic daemon.err node-red:     at doWrite (_stream_writable.js:415:12)
Dec 26 16:48:08 Homematic daemon.err node-red:     at writeOrBuffer (_stream_writable.js:399:5)
Dec 26 16:48:08 Homematic daemon.err node-red:     at Receiver.Writable.write (_stream_writable.js:299:11)
Dec 26 16:48:08 Homematic daemon.err node-red:     at Socket.socketOnData (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-deconz/node_modules/ws/lib/websocket.js:875:35)
Dec 26 16:48:08 Homematic daemon.err node-red:     at Socket.emit (events.js:198:13)
Dec 26 16:48:08 Homematic daemon.err node-red:     at Socket.EventEmitter.emit (domain.js:448:20)
Dec 26 16:48:08 Homematic daemon.err node-red:     at addChunk (_stream_readable.js:287:12)`

** Hardware / Software **
  - Deconz Synology Docker  
  - raspberry 2 (Node Red)
  - version of deconz gateway: [2.05.69 / 06/09/2019] 
  - version of node-red-contrib-deconz: [1.1.9]

**Comment by andreypopov** [comment]
+ node-red-contrib-deconz@1.1.10

**Comment by andreypopov** [comment]
any news?
