### ISSUE TITLE
Xiaomi BUTTON sends press+longpress event together

### ISSUE THREAD

**Issue by elpaso666** [andreypopov/node-red-contrib-deconz#52]
Hi,

1. do you have somewhere documentation about codes/integers being send/captured from Phoscon/Connbee? for Xiaomi button it is 1000-1001-etc

2. is there a reason that message 1001 for long press has also message 1000 as single press before? Somehow it makes sense that longpress is actually a press, but it is hard to assign different action on it, as for long press I also get standard press

thank you!
Jakub

**Comment by andreypopov** [comment]
1. REST API: https://dresden-elektronik.github.io/deconz-rest-doc/
2. https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi-WXKG01LM

1000 | One | initial press
-- | -- | --
1001 | One | single hold
1002 | One | single short release
1003 | One | single hold release
1004 | One | double short press
1005 | One | triple short press
1006 | One | quad short press
1010 | One | five+ short press

**Comment by elpaso666** [comment]
thx, works correctly:

var name = "SW5";

var value = msg.payload;

if ( value == "1002" )
{
msg.payload = name+"-single";
return msg;
} 

else if (value == "1004") 
{
msg.payload = name+"-double";
return msg;
}

else if (value == "1001") 
{
msg.payload = name+"-LP";
return msg;
}

else if (value == "1003") 
{
msg.payload = name+"-LR";
return msg;
}
