### ISSUE TITLE
missing 0-100% for dimmable lights

### ISSUE THREAD

**Issue by elpaso666** [andreypopov/node-red-contrib-deconz#55]
Hello,

would it be possible to have dimable input for HUE lights with values of 0-100%, my source sends % values, so 255 is out of scope :)

Why there is 0-255 as value? Is it solvable or should I write a function to rewrite 0-100 -> 0-255 with lineary correlation?

thx
Jakub

**Comment by elpaso666** [comment]
it is very easily solvable with middle function of msg.payload = 255 / 100 * lightdim;

how ever it would be nice to have an option to access % directly, I believe many sources like Loxone operates on % basis.

Jakub

**Comment by andreypopov** [comment]
Range node?

![2020-01-02_12-20-52](https://user-images.githubusercontent.com/1624839/71659918-5a173b80-2d5a-11ea-9103-3cc7dd7738d0.png)

**Comment by andreypopov** [comment]
I use it in both ends
![2020-01-02_12-22-04](https://user-images.githubusercontent.com/1624839/71659964-86cb5300-2d5a-11ea-9bec-7157c2c85aa4.png)

**Comment by elpaso666** [comment]
oh, cool! thx so much I really appreaciate, it is hard for a "dev/nodered/js" rookie to get allll the possibilities.

is this place OK for you to solve similar things? I will try to integrate today a color HUE lamp, where I have a fear I will have to also somehow correct the values comming from Loxone home automatization system. I can have it in RGB format, which is different then HUE RGB.

Jakub
