### ISSUE TITLE
HUE Lamp input (HSV or RGB)

### ISSUE THREAD

**Issue by elpaso666** [andreypopov/node-red-contrib-deconz#56]
Hi Andrey,

would it be possible to check if following input for colored HUE lamp could be somehow integrated:

1. object created by transformation of HSV format to RGB using https://gist.github.com/sstroot/a2be61a889a6e6712fa0591ab1a69e35#comments

msg.payload : Object
object
	on: true
rgb: array[3]
0: 20
1: 55
2: 112
brightness: "44"

2. my Loxone system supports only HSV output: 
"hsv(217,82,44)"

thank you very much!
Jakub
![Capture](https://user-images.githubusercontent.com/7722883/71689769-290f2900-2da3-11ea-8e80-40d3919873a8.PNG)

**Comment by elpaso666** [comment]
I tried to pass only msg.payload.brightness from my function to the HUE Lamp while setting the Deconz-in as:
- command brightness (0-255)
- and passing the value with you recommended RANGE NODE
- debug confirm the number 0-255 going out in RANGE NODE
- but light is not doing anything

thx

**Comment by andreypopov** [comment]
Try to use https://flows.nodered.org/node/node-red-contrib-color-convert
I dont want to re-write existing plugins and copy theirs functionality

Write here if it helps.

**Comment by elpaso666** [comment]
I have this one already. I am a bit lost in:

- the Deconz-IN node and what format it expects to receive for full control of the Color bulb?
- what is HUE in format of 0....65535. I am not able to find how to convert the HUE (0...255) to HUE (0...65535) or RANGE could be enough?

I am already able to send brightness and saturation separately and it works perfectly.

thank you a lot for you support Andrey!

When I have this running I will put together a complete wiki page for Loxone<>Conbeen integration for the Loxone community.

Jakub

**Comment by andreypopov** [comment]
easy, RANGE node for HUE [0, 65535], [0, 360]

**Comment by elpaso666** [comment]
ah, ok I try.

can you please also advise about the full msg.payload the Decon-IN expects for full controll of the bulb?

**Comment by andreypopov** [comment]
https://dresden-elektronik.github.io/deconz-rest-doc/lights/
I use REST API, here you can find all parameters.

**Comment by elpaso666** [comment]
yes, this I saw. But I am wondering which "Command" should I set on the DeconZ-OUT node to make sure all the parameters are passed to the bulb?

single HUE, SAT, BRI are working, but I am not sure about togethwe/combination.

thank you

**Comment by andreypopov** [comment]
Choose object-json in OUT node and set

![2020-01-03_14-09-54](https://user-images.githubusercontent.com/1624839/71720426-c1a0ba00-2e32-11ea-95a0-4b54fae47e11.png)

**Comment by elpaso666** [comment]
thank you! all works perfectly!

Jakub

**Comment by andreypopov** [comment]
nice ,good job:)

**Comment by elpaso666** [comment]
even as my 1st NodeRed sub-flow with detection of WHITE or COLOR bulb :)

thx for guidance!
