### ISSUE TITLE
Xiaomi Aqara Switch does not support tripple quadro press

### ISSUE THREAD

**Issue by MeisterQ** [andreypopov/node-red-contrib-deconz#58]
The Xiaomi Mijia Smart Switch (The old round one) Supports Single, double, triple, quadro, more, and long press.

But the new Xiaomi Aqara Smart Switch (The new square one) supports only single, double and long press.

  - raspberry 4   
  - version of deconz gateway: 2.05.72 / 12.12.2019 Firmware 264A0700
  - version of node-red-contrib-deconz: 1.1.10

**Comment by andreypopov** [comment]
I catch data from deconz plugin.  I cant fix it,  please, create issue in deconz repo.
