### ISSUE TITLE
I would be willing to support via a paypal donation

### ISSUE THREAD

**Issue by MattL0** [andreypopov/node-red-contrib-deconz#59]
** Describe your idea here**
Support via Paypal donation would be better I think.

**Comment by andreypopov** [comment]
Hi, thanks but it is impossible in my country.

**Comment by andreypopov** [comment]
you can try https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7K56E4PQ35LWY&source=url
but i dont know if it will work

**Comment by MattL0** [comment]
No , it sais ‘’sorry there is problem ‘’ at the end

**Comment by andreypopov** [comment]
The only one way is 
https://support.patreon.com/hc/en-us/articles/204606215-Can-I-make-a-one-time-payment-
