### ISSUE TITLE
unable to get API Key

### ISSUE THREAD

**Issue by ajdezigns** [andreypopov/node-red-contrib-deconz#60]
Hi all I've been using this plugin for a while but I went through a few upgrades like last month and I've lost all access I've uninstalled and reinstalled the add on and ensured nodered, home assistant, and deconz are all up to date but it just keeps throwing me this error message.

`WebSocket error: Error: connect ECONNREFUSED 192.168.0.71:8081`

**Comment by andreypopov** [comment]
docker? is port correct?
8081 looks like http port, by deault socket is on 443

**Comment by Klopskind** [comment]
Same here. I think it has something to do with the Hassio Deconz Addon changing to Ingress. With release 3.9. the node-red-contrib-deconz worked fine, but in release 5.+ (i skipped 4) it does not work anymore.
I tried all different ports and so on, but can't get a key in NodeRed.

**Comment by Starkstroemer** [comment]
Same Problem. Is there another way to get the api key? I use deConz, Node Red and Phoscon.

**Comment by andreypopov** [comment]
Manually. 
I got it with this manual https://sprut.ai/client/article/550 (but it is in russian! use translator)

http://dresden-elektronik.github.io/deconz-rest-doc/configuration/#aquireapikey

**Comment by andreypopov** [comment]
Try to open https://phoscon.de/discover from your network. What do you see?





> Same here. I think it has something to do with the Hassio Deconz Addon changing to Ingress. With release 3.9. the node-red-contrib-deconz worked fine, but in release 5.+ (i skipped 4) it does not work anymore.
> I tried all different ports and so on, but can't get a key in NodeRed.

please, describe step-by-step, what did you install, I will try to emulate your installation

**Comment by Starkstroemer** [comment]
Suprise, suprise...it's running. Thx for ur support!

**Comment by andreypopov** [comment]
lol ) I installed HA, deconz on clean RPI )

**Comment by DeepHyperspace** [comment]
Hey i got the same issue, when i click on "get settings" nothing happens at all. I've managed to get an API-Key with the "node-red-contrib-huemagic" for philipps hue. It also finds the deCONZ instance and can connect to that. Afterwards you can copy the API-Key to the "node-red-contrib-deconz" config. 

Just a workaround till it is fixed

**Comment by andreypopov** [comment]
go here for answer
https://github.com/andreypopov/node-red-contrib-deconz/issues/65
