### ISSUE TITLE
Better support for Thermostats (e.g. Eurotronics Spirit)

### ISSUE THREAD

**Issue by Sk4zz** [andreypopov/node-red-contrib-deconz#61]
For various reasons I want to build a MQTT interface for my Eurotronics Spirit TRVs. It would be great, if support through the node-red plugin for thermostats could be improved. 

Right now I can retrieve the properties `lastupdated`, `on`, `valve` and `temperature` via `in` and `get` nodes. And I am not able to access the TRVs via `out` node at all (they just don't show up in the list of devices).

Is it possible to add support for reading and setting `heatsetpoint` and `mode` through the nodered plugin?

Thank you!

**Comment by andreypopov** [comment]
Leave this question for DECONZ: https://github.com/dresden-elektronik/deconz-rest-plugin/issues
I dont support hardware, my plugin is a bridge between node-red and deconz REST API
They give me the list of available parameters.
