### ISSUE TITLE
Send multiple settings to a light group

### ISSUE THREAD

**Issue by Webunity** [andreypopov/node-red-contrib-deconz#64]
On motion detection i want my outdoor lights to change both temperature and brightness. This currently needs 2 node-calls whereas the API should support both combined in 1 API call towards Deconz. Would it be possible to add an 'expert' node which is able to send JSON to the API? Or any other idea you might have to facilitate this?

**e.g. sample request data taken from the [documentation](https://dresden-elektronik.github.io/deconz-rest-doc/lights/#setstate)**
```
{
  "on": true,
  "bri": 180,
  "hue": 43680,
  "sat": 255,
  "transitiontime": 10
}
```

**Comment by andreypopov** [comment]
yes, you can 

![2020-02-04_14-41-28](https://user-images.githubusercontent.com/1624839/73741991-75f86d80-475c-11ea-8f21-adc25af50201.png)

**Comment by Webunity** [comment]
great 👍 👍
