### ISSUE TITLE
"Get Settings" button only discovers second gateway in network

### ISSUE THREAD

**Issue by christmasjumper** [andreypopov/node-red-contrib-deconz#65]
Hi,

When trying to configure a new server, I enter the address of what I consider to be my primary deeconz device (e.g 10.0.1.150) - When I click the "Get Settings" button to get the API key an error message is displaying saying "lnk button not pressed" - the IP address in the server field then switches to my second deeconz device (e.g 10.0.1.151) - it is then impossible to get it to get the API key for the first.

I have tried this with the "Authenticate App" button pressed on the first deconz gateway only (10.0.1.150) - I have then tried it with the button pressed on the second gateway, when I do this the server configuration details change to the second gateway and it does populate an API key.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/34621859/73929419-ab23cd80-48cc-11ea-96cf-8dac707c191b.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/34621859/73929454-b971e980-48cc-11ea-92ca-82e3b6c8e3dd.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/34621859/73929479-c1ca2480-48cc-11ea-8e0b-7f07a052e481.png">

I only use the second deconz as a development / test box, so I don't have all my devices added to it.

  - raspberry 3  
  - version of deconz gateway: 2.05.69
  - version of node-red-contrib-deconz: 1.1.10

**Comment by andreypopov** [comment]
it is not bug, some ports are closed, impossible to get settings
try to get api manually 

btw "get settings" needs Internet access

**Comment by christmasjumper** [comment]
OK. I have internet access from the network where both nodered and deconz resides, there is nothing that would be filtering any ports on the first deconz box, so a bit confused. Where would the open ports be missing? Docker side? On my WAN firewall? or on Deconz box?

I tried the discovery URL and it returns both boxes, albeit the secondary box is listed first for some reason.

**Comment by andreypopov** [comment]
I made workaround for hassio in  **node-red-contrib-deconz@1.1.11**

![2020-02-26_21-35-52](https://user-images.githubusercontent.com/1624839/75376401-0a2f9d80-58e1-11ea-99dc-a9e07ae64d83.png)
![2020-02-26_21-35-21](https://user-images.githubusercontent.com/1624839/75376395-08fe7080-58e1-11ea-9a42-43d0b7361f4f.png)
