### ISSUE TITLE
color temperature "ct" does not change

### ISSUE THREAD

**Issue by guewii** [andreypopov/node-red-contrib-deconz#66]
Hi!
I have a problem, the color temperature "ct" does not change on my Osram Lightify´s
Field: ct
Type: Number (153..500)
Description: Set the Mired color temperature of the light. (2000K - 6500K)

do you have an idea? :-/

** Screens / Logs **
![grafik](https://user-images.githubusercontent.com/49875844/74384297-40552380-4df1-11ea-9c63-ae1d79a2e8bd.png)

** Hardware / Software **
  - raspberry 3   
  - version of deconz gateway: [2.05.72 / 12/12/2019] 
  - version of node-red-contrib-deconz: [1.1.10]

**Comment by andreypopov** [comment]
hi, only for test try to change CT with out node, choose Color Temperature

**Comment by guewii** [comment]
hi, in the Phoscon WebUI i can change the color temperature.

**Comment by guewii** [comment]
Hi again!

I found the problem :-)

It was just a firmware problem of my OSRAM Lightifys (Tunable White GU10)
so i updated from v.1.03.07 to v.1.05.10 and everything works fine.
