### ISSUE TITLE
Server node doesn't appear to be installed

### ISSUE THREAD

**Issue by chrisg2003** [andreypopov/node-red-contrib-deconz#67]
Hi

I am using the node addon with Node Red. When it installed it reported 6 new nodes but only 5 appear in the node list.

The guide says to deploy the Server but how do I do this?

I am new to this and may well have made a simple error.

Thanks for you comment

**Comment by andreypopov** [comment]
5 nodes + 1 server (hidden)
fill settings, click done, click Deploy

**Comment by chrisg2003** [comment]
Thank you for your very prompt reply, it is now working.
You have been most helpful and thank you for your work.

**Comment by chrisg2003** [comment]
Thanks once again.
