### ISSUE TITLE
Aquara Motion Senzor - Lux senzor

### ISSUE THREAD

**Issue by elpaso666** [andreypopov/node-red-contrib-deconz#68]
Hi,

the lux metter is integrated in complete msg object, but only within thresholds, which I have no idea how to modify (they are coming like parameters). On top the LUX value is not being taken at all.

![image](https://user-images.githubusercontent.com/7722883/76677102-ab4d7200-65ca-11ea-8bb5-47e99d5049ea.png)

thank you

**Comment by andreypopov** [comment]
I only take the data that gives me deconz.  Please, go to deconz github and create issue there.

**Comment by elpaso666** [comment]
will do so! thx
