### ISSUE TITLE
Feature request: make it possible to call groups in the out module. 

### ISSUE THREAD

**Issue by vandalon** [andreypopov/node-red-contrib-deconz#7]
** Describe your idea here**

It would be great to be able to turn of light (deconz) groups in one go, instead of having an out item for every light.

**Comment by andreypopov** [comment]
this?

![2019-07-09_18-22-22](https://user-images.githubusercontent.com/1624839/60901401-8d2eb580-a276-11e9-997f-ff3ca50daacd.png)

**Comment by vandalon** [comment]
i'm idiot, scratch that.
