### ISSUE TITLE
Support Thermostat payload

### ISSUE THREAD

**Issue by emme73** [andreypopov/node-red-contrib-deconz#72]
I use to command an Eurotronic radiator thermostat from deConz to Home Assistant
It would be nice to get support for it in the NodeRed Contrib nodes

Actually you can only get the status but not set it, the out node does not list the device.

thanks

**Comment by andreypopov** [comment]
should list, the list is the same for all nodes

**Comment by emme73** [comment]
Thermostat device is not listed in the OUT node:

this is the list of available OUT devices:
![image](https://user-images.githubusercontent.com/26736389/78016842-a79c4800-734b-11ea-88b1-b5e9a81526f5.png)

and this is the list of available IN Devices under group Devices (thermostat device is SPZB0001)
![image](https://user-images.githubusercontent.com/26736389/78016911-c3075300-734b-11ea-94ff-0ea11163853b.png)

**Comment by andreypopov** [comment]
Does phoscon app list it?

**Comment by emme73** [comment]
Hi, sorry for late reply,
no phoson APP does not list thermostat devices, so I assume deConz node depends on it

**Comment by andreypopov** [comment]
I can do nothing with it. Open request in deconz repo
