### ISSUE TITLE
Xiaomi Door/Window Sensor not updating status

### ISSUE THREAD

**Issue by bonelessc** [andreypopov/node-red-contrib-deconz#75]
Hi!

First of all, thanks for a great package, it has been working great for me so far!

I have ran into a little issue tho. I have a couple of xiaomi door/window sensors, I have added these to my flow and they don't seem to be updating.

If I select the "send state on start", I do receive the initial state (with correct update time). Sensor seems to be updating correctly in the Deconz web app.

Any ideas?

Thanks!

**Comment by andreypopov** [comment]
No ideas.. 
looks like websocket error..

**Comment by bonelessc** [comment]
Thank you for the quick response!
Wouldn't that influence my other devices too? Everything else is working great. This particular sensor is reporting fine through DeConz into home assistant as well.

**Comment by andreypopov** [comment]
try to remove node and add it again

**Comment by bonelessc** [comment]
Now I feel silly... That worked like a charm! Sorry to bother you for something that stupid!

Thanks again tho!!
