### ISSUE TITLE
Begin/End Increasing/Decreasing Brightness Commands

### ISSUE THREAD

**Issue by ryancasler** [andreypopov/node-red-contrib-deconz#79]
In order to control lights similarly to the way that you can from remotes connected directly to Deconz, it would be nice if we could issue commands from the out node that would cause the brightness to begin increasing and then be able to stop that transition.  This is done via the Hue api by ordering a brightness setting of max for the up direction or 0 for the down direction, with a transition time.  Then to stop the transition, you order a bri_inc or 0.  This stops the transition at whatever level the light is current at.  This allows you to hold the button on a remote and then release it to have the light set to the brightness that is currently displayed.  

It would be nice if we could do that from the out node.  This would allow you to use other devices as remotes for Deconz connected lights.

**Comment by andreypopov** [comment]
hi! I will not add new features, plugin will support only deconz REST API methods and options
https://dresden-elektronik.github.io/deconz-rest-doc/lights/

I am working on new z2m plugin: https://github.com/andreypopov/node-red-contrib-zigbee2mqtt

It supports brightness move.
https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttfriendly_nameset

**Comment by ryancasler** [comment]
> It supports brightness move.

I don;t see "brightness_move" as a command.  Where would that be located?  That is exactly what I'm looking for.  These are the commands as I see them today:
![image](https://user-images.githubusercontent.com/30270489/83296087-1b2ccb00-a1be-11ea-9fec-55de1dfecac5.png)

**Comment by ryancasler** [comment]
Still wondering how to send brightness move from the this node.  Any clarification you could provide would be appreciated.

**Comment by ryancasler** [comment]
I attempted to send {"brightness_move": 30} as a JSON command but it comes back as parameter not available just like "brightness" does.  So, I would like to know how this should be set up.  I really don't think this basic question is asking too much.

**Comment by ryancasler** [comment]
Never mind.....I figured it out myself.  It's actually not Brightness_move but instead is "bri_inc" along with the amount you want to change.  So, to brighten it's 255 to dim it's -255.  That along with "transitiontime" gets you the brightening or fading.  Then when you want to stop it's bri_inc equal to 0.
