### ISSUE TITLE
Possibility to select multiple sensors in one IN node. 

### ISSUE THREAD

**Issue by vandalon** [andreypopov/node-red-contrib-deconz#8]
** Describe your idea here**
I think it would be nice to have the option to select multiple (motion) sensors in one IN-node.
This could be useful for rooms with multiple sensors and/or group all the motion sensors for notification reasons.

**Comment by andreypopov** [comment]
Effort level: **high**
- breaking changes;
- development time;

Necessity level: **low** 
- you can use several nodes, if u need; 
- will not give new opportunities;
- impossible to use with homekit;
