### ISSUE TITLE
Copying Payload path is wrong case

### ISSUE THREAD

**Issue by Roysteroonie** [andreypopov/node-red-contrib-deconz#83]
If you copy the payload path for Xiaomi switches, it gives you payload.On
Its not payload.On, its payload.on.
Using uppercase O stops the flow.

**Comment by andreypopov** [comment]
homekit output ?

**Comment by Roysteroonie** [comment]
Hi, after updating over this weekend, I can no longer reproduce the issue. Many thanks for all you do ;)
