### ISSUE TITLE
Deconz out node with homekit payload type

### ISSUE THREAD

**Issue by TheNON75** [andreypopov/node-red-contrib-deconz#92]
Hi All,

I have some deconz based flows which are working as intended in general.
The deconz out nodes are set to expect homekit payload type, which works if the payload is coming from a homekit node.
In case I would like to send a payload of this type from a function node, the deconz out node ignores the payload and nothing happens. The reason for trying this is, that I would like to avoid using duplicate out nodes for the same accessory.
Msg I tried:

`{"_msgid":"be80185.0e22ae8","payload":{"Saturation":92,"Hue":42,"Brightness":100,"On":true},"topic":"light","hap":{},"name":"Bed Light"}`

I appreciate any useful hints

Thanks

**Comment by DrX7FFF** [comment]
+1

**Comment by TheNON75** [comment]
created a bug on this
https://github.com/andreypopov/node-red-contrib-deconz/issues/96#issue-729099548
