### ISSUE TITLE
Partially no Button Events from Hue Dimmer

### ISSUE THREAD

**Issue by goofy1988** [andreypopov/node-red-contrib-deconz#93]
Forst of all thabk you for your great effort in maintaining this awesome Nodes.

I wonder if anyoneelse having right now problems to get the buttonstates from in deconz integrated hue dimmer switches?
Mostly i having issues receiving button states for dim up and dim down. 
I would not ask if that would be a new installation, but it was working flawless for me from the beginning, over a year. Now this issues come alive. 
Maybe others having the same issues and its in someway related to the nodes itself?

Thanks.

Best regards
Dominik

** Hardware / Software **
  - raspberry 4 
Openhab, Nodered 1.1

**Comment by TheNON75** [comment]
Do you get button events in your openhab?

**Comment by goofy1988** [comment]
Hello,
I will give a feedback. It was an issue with the Zigbee Channel. So the problem had nothing to do with the nodes.  

Thanks alot
